sudo make clean
make nostart file=button
make nostart file=switch
make nostart file=switches 
make nostart file=blink
make nostart file=blink_single
make nostart file=usb_uart_simple 
make nostart file=usb_uart_parse 
make nostart file=keyboard_uart
make nostart file=keyboard_uart
make nostart file=ps2_led
make nostart file=vga_simple